export type Page = 'dashboard' | 'analytics' | 'logic' | 'settings' | 'demo'
export type Phase = 'vehicle_green' | 'warning' | 'all_red_to_ped' | 'pedestrian_green' | 'all_red_to_vehicle'
export type PhasePlan = Record<Phase, number>
export type Scenario = { id: string; name: string; description: string; duration: number; tone: string }
export type Config = { control_mode: 'adaptive' | 'manual'; phase_plan: PhasePlan; min_vehicle_green: number; low_flow_threshold: number; group_threshold: number; max_single_wait: number; max_group_wait: number; pedestrian_green: number }
export type Frame = { time: number; phase: Phase; mode: 'adaptive' | 'manual' | 'fallback' | 'fixed'; healthy: boolean; vehicles: number | null; vehicle_positions: number[]; pedestrians: number | null; on_road?: number | null; flow_per_min: number | null; clear_gap: boolean; waiting_seconds: number; reason: string }
export type Event = { time: number; type: string; text: string; phase?: Phase }
export type Summary = { vehicles: number; pedestrians: number; peak_pedestrians: number; mean_flow_per_min: number | null; peak_flow_per_min: number | null; mean_vehicles_in_zone: number | null; peak_vehicles_in_zone: number | null; mean_wait: number | null; max_wait: number | null; first_pedestrian_green: number | null; phase_switches: number; served_requests: number; unserved_requests: number; camera_uptime: number; safety_violations: number }
export type Report = { scenario_id: string; scenario: Scenario; config: Config; frames: Frame[]; events: Event[]; summary: Summary; baseline: Summary; modeled_wait_difference: number | null; recommendation: string; disclaimer: string }
